//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties({ "powergridId",
"setPowergridId"})
public class Branch
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected int powergridId;
    protected int fromBusNumber;
    protected int toBusNumber;
    protected int indexNum;
    protected String ckt;
    protected double r;
    protected double x;
    protected double rating;
    protected double rateA;
    protected double rateB;
    protected double rateC;
    protected int status;
    protected double p;
    protected double q;
    protected String mrid;
    protected double bCap;
    protected double ratio;
    protected double angle;
      

    public double getbCap() {
		return bCap;
	}

	public void setbCap(double bCap) {
		this.bCap = bCap;
	}

	public double getRatio() {
		return ratio;
	}

	public void setRatio(double ratio) {
		this.ratio = ratio;
	}

	public double getAngle() {
		return angle;
	}

	public void setAngle(double angle) {
		this.angle = angle;
	}

	public boolean isSetBranchId() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }

    /**
     * Gets the value of the fromBusNumber property.
     * 
     */
    public int getFromBusNumber() {
        return fromBusNumber;
    }

    /**
     * Sets the value of the fromBusNumber property.
     * 
     */
    public void setFromBusNumber(int value) {
        this.fromBusNumber = value;
    }

    public boolean isSetFromBusNumber() {
        return true;
    }

    /**
     * Gets the value of the toBusNumber property.
     * 
     */
    public int getToBusNumber() {
        return toBusNumber;
    }

    /**
     * Sets the value of the toBusNumber property.
     * 
     */
    public void setToBusNumber(int value) {
        this.toBusNumber = value;
    }

    public boolean isSetToBusNumber() {
        return true;
    }

    /**
     * Gets the value of the indexNum property.
     * 
     */
    public int getIndexNum() {
        return indexNum;
    }

    /**
     * Sets the value of the indexNum property.
     * 
     */
    public void setIndexNum(int value) {
        this.indexNum = value;
    }

    public boolean isSetIndexNum() {
        return true;
    }

    /**
     * Gets the value of the ckt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCkt() {
        return ckt;
    }

    /**
     * Sets the value of the ckt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCkt(String value) {
        this.ckt = value;
    }

    public boolean isSetCkt() {
        return (this.ckt!= null);
    }

    /**
     * Gets the value of the r property.
     * 
     */
    public double getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     */
    public void setR(double value) {
        this.r = value;
    }

    public boolean isSetR() {
        return true;
    }

    /**
     * Gets the value of the x property.
     * 
     */
    public double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     */
    public void setX(double value) {
        this.x = value;
    }

    public boolean isSetX() {
        return true;
    }

    /**
     * Gets the value of the rating property.
     * 
     */
    public double getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     */
    public void setRating(double value) {
        this.rating = value;
    }

    public boolean isSetRating() {
        return true;
    }

    /**
     * Gets the value of the rateA property.
     * 
     */
    public double getRateA() {
        return rateA;
    }

    /**
     * Sets the value of the rateA property.
     * 
     */
    public void setRateA(double value) {
        this.rateA = value;
    }

    public boolean isSetRateA() {
        return true;
    }

    /**
     * Gets the value of the rateB property.
     * 
     */
    public double getRateB() {
        return rateB;
    }

    /**
     * Sets the value of the rateB property.
     * 
     */
    public void setRateB(double value) {
        this.rateB = value;
    }

    public boolean isSetRateB() {
        return true;
    }

    /**
     * Gets the value of the rateC property.
     * 
     */
    public double getRateC() {
        return rateC;
    }

    /**
     * Sets the value of the rateC property.
     * 
     */
    public void setRateC(double value) {
        this.rateC = value;
    }

    public boolean isSetRateC() {
        return true;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public int getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(int value) {
        this.status = value;
    }

    public boolean isSetStatus() {
        return true;
    }

    /**
     * Gets the value of the p property.
     * 
     */
    public double getP() {
        return p;
    }

    /**
     * Sets the value of the p property.
     * 
     */
    public void setP(double value) {
        this.p = value;
    }

    public boolean isSetP() {
        return true;
    }

    /**
     * Gets the value of the q property.
     * 
     */
    public double getQ() {
        return q;
    }

    /**
     * Sets the value of the q property.
     * 
     */
    public void setQ(double value) {
        this.q = value;
    }

    public boolean isSetQ() {
        return true;
    }

    /**
     * Gets the value of the mrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrid() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrid(String value) {
        this.mrid = value;
    }

    public boolean isSetMrid() {
        return (this.mrid!= null);
    }

}
