//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties({ "powergridId",
	"setPowergridId"})
public class Bus
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    protected int busNumber;
    protected int powergridId;
    protected String substationName;
    protected String busName;
    protected double baseKv;
    protected int code;
    protected double pl;    
    protected double ql;
    protected double gl;
    protected double bl;
    protected int areaId;
    protected double va;
    protected double vm;
    protected int zoneId;
    protected String mrid;
    protected double totalPLoad;
    protected double totalQLoad;
    protected double totalPGen;
    protected double totalQGen;   

    public double getTotalPLoad() {
		return totalPLoad;
	}

	public void setTotalPLoad(double totalPLoad) {
		this.totalPLoad = totalPLoad;
	}

	public double getTotalQLoad() {
		return totalQLoad;
	}

	public void setTotalQLoad(double totalQLoad) {
		this.totalQLoad = totalQLoad;
	}

	public double getTotalPGen() {
		return totalPGen;
	}

	public void setTotalPGen(double totalPGen) {
		this.totalPGen = totalPGen;
	}

	public double getTotalQGen() {
		return totalQGen;
	}

	public void setTotalQGen(double totalQGen) {
		this.totalQGen = totalQGen;
	}

	/**
     * Gets the value of the busNumber property.
     * 
     */
    public int getBusNumber() {
        return busNumber;
    }

    /**
     * Sets the value of the busNumber property.
     * 
     */
    public void setBusNumber(int value) {
        this.busNumber = value;
    }

    public boolean isSetBusNumber() {
        return true;
    }

    /**
     * Gets the value of the powergridId property.
     * 
     */
    public int getPowergridId() {
        return powergridId;
    }

    /**
     * Sets the value of the powergridId property.
     * 
     */
    public void setPowergridId(int value) {
        this.powergridId = value;
    }

    public boolean isSetPowergridId() {
        return true;
    }


    /**
     * Gets the value of the busName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusName() {
        return busName;
    }

    /**
     * Sets the value of the busName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusName(String value) {
        this.busName = value;
    }

    public boolean isSetBusName() {
        return (this.busName!= null);
    }

    /**
     * Gets the value of the substationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstationName() {
        return substationName;
    }

    /**
     * Sets the value of the substationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstationName(String value) {
        this.substationName = value;
    }

    public boolean isSetSubstationName() {
        return (this.substationName!= null);
    }
    

    /**
     * Gets the value of the baseKv property.
     * 
     */
    public double getBaseKv() {
        return baseKv;
    }

    /**
     * Sets the value of the baseKv property.
     * 
     */
    public void setBaseKv(double value) {
        this.baseKv = value;
    }

    public boolean isSetBaseKv() {
        return true;
    }

    /**
     * Gets the value of the code property.
     * 
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     */
    public void setCode(int value) {
        this.code = value;
    }

    public boolean isSetCode() {
        return true;
    }

    /**
     * Gets the value of the pl property.
     * 
     */
    public double getPl() {
        return pl;
    }

    /**
     * Sets the value of the pl property.
     * 
     */
    public void setPl(double value) {
        this.pl = value;
    }

    public boolean isSetPl() {
        return true;
    }

    /**
     * Gets the value of the ql property.
     * 
     */
    public double getQl() {
        return ql;
    }

    /**
     * Sets the value of the ql property.
     * 
     */
    public void setQl(double value) {
        this.ql = value;
    }

    public boolean isSetQl() {
        return true;
    }

    /**
     * Gets the value of the gl property.
     * 
     */
    public double getGl() {
        return gl;
    }

    /**
     * Sets the value of the gl property.
     * 
     */
    public void setGl(double value) {
        this.gl = value;
    }

    public boolean isSetGl() {
        return true;
    }

    /**
     * Gets the value of the bl property.
     * 
     */
    public double getBl() {
        return bl;
    }

    /**
     * Sets the value of the bl property.
     * 
     */
    public void setBl(double value) {
        this.bl = value;
    }

    public boolean isSetBl() {
        return true;
    }

    /**
     * Gets the value of the areaId property.
     * 
     */
    public int getAreaNumber() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     */
    public void setAreaId(int value) {
        this.areaId = value;
    }

    public boolean isSetAreaId() {
        return true;
    }

    /**
     * Gets the value of the va property.
     * 
     */
    public double getVa() {
        return va;
    }

    /**
     * Sets the value of the va property.
     * 
     */
    public void setVa(double value) {
        this.va = value;
    }

    public boolean isSetVa() {
        return true;
    }

    /**
     * Gets the value of the vm property.
     * 
     */
    public double getVm() {
        return vm;
    }

    /**
     * Sets the value of the vm property.
     * 
     */
    public void setVm(double value) {
        this.vm = value;
    }

    public boolean isSetVm() {
        return true;
    }

    /**
     * Gets the value of the zoneId property.
     * 
     */
    public int getZoneNumber() {
        return zoneId;
    }

    /**
     * Sets the value of the zoneId property.
     * 
     */
    public void setZoneId(int value) {
        this.zoneId = value;
    }

    public boolean isSetZoneId() {
        return true;
    }

    /**
     * Gets the value of the mrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrid() {
        return mrid;
    }

    /**
     * Sets the value of the mrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrid(String value) {
        this.mrid = value;
    }

    public boolean isSetMrid() {
        return (this.mrid!= null);
    }

}
