//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.12 at 11:59:10 AM PDT 
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PowergridRating complex type.
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PowergridRating", propOrder = {
    "powergridRatingId",
    "powergridId",
    "user",
    "rating",
    "comment",
    "created",
    "mrid"
})
public class PowergridRating
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "PowerGridRatingId")
    protected int powerGridRatingId;
    @XmlElement(name = "PowerGridId")
    protected int powergridId;
    @XmlElement(name = "User", required = true)
    protected String user;
    @XmlElement(name = "Rating", required = true)
    protected int rating;
    @XmlElement(name = "Comment", required = true)
    protected String comment;
    @XmlElement(name = "Created", required = true)
    protected Date created;
    @XmlElement(name = "Mrid")
    protected String mrid;
    
	public int getPowergridId() {
		return powergridId;
	}
	public void setPowergridId(int powergridId) {
		this.powergridId = powergridId;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public int getRating() {
		return rating;
	}
	public void setRating(int rating) {
		this.rating = rating;
	}
	public String getComment() {
		return comment;
	}
	public void setComment(String comment) {
		this.comment = comment;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public int getPowerGridRatingId() {
		return powerGridRatingId;
	}
	public void setPowerGridRatingId(int powerGridRatingId) {
		this.powerGridRatingId = powerGridRatingId;
	}
	public String getMrid() {
		return mrid;
	}
	public void setMrid(String mrid) {
		this.mrid = mrid;
	}


}
