//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.03.12 at 11:59:10 AM PDT
//


package pnnl.goss.powergrid.datamodel;

import java.io.Serializable;


public class PowergridDetail
    implements Serializable
{

	public final static String POWERGRID_DETAIL_DATATYPE = "PowergridDetail";

	private final static long serialVersionUID = 123432L;

//	"{\"id\":\"1\",\"name\":\"Greek 118\",\"created_by\":\"Poorva Sharma\",\"filename\":\"Greepti118.raw\",\"desc\":\"this is a test\",\"format\":\"PTI(23,26,29,31)\",\"useraccess\":\"Public\"}"
	
    protected int powergridId;
    protected String powerGridName;
    protected String modelFormat;
    private String createdBy;
    private String description;
    private String originalFilename;
    private String accessLevel;
    private String createdOn;
    
    
    
	public int getPowergridId() {
		return powergridId;
	}
	public void setPowergridId(int powergridId) {
		this.powergridId = powergridId;
	}
	public String getPowerGridName() {
		return powerGridName;
	}
	public void setPowerGridName(String powerGridName) {
		this.powerGridName = powerGridName;
	}
	public String getModelFormat() {
		return modelFormat;
	}
	public void setModelFormat(String modelFormat) {
		this.modelFormat = modelFormat;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getOriginalFilename() {
		return originalFilename;
	}
	public void setOriginalFilename(String originalFilename) {
		this.originalFilename = originalFilename;
	}
	public String getAccessLevel() {
		return accessLevel;
	}
	public void setAccessLevel(String accessLevel) {
		this.accessLevel = accessLevel;
	}
	public String getCreatedOn() {
		return createdOn;
	}
	public void setCreatedOn(String createdOn) {
		this.createdOn = createdOn;
	}   
	
	
    
}
